image: Visual Studio 2022
configuration: Release

install:
  - choco install gitversion.portable -pre -y

dotnet_csproj:
  patch: false

before_build:
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver 
  - ps: $env:Version        = $env:GitVersion_MajorMinorPatch
  - ps: $env:FileVersion    = $env:GitVersion_AssemblySemFileVer
  - ps: $env:AssemblyVersion= $env:GitVersion_AssemblySemVer
  - ps: $env:PackageVersion = $env:GitVersion_FullSemVer

build:
  project: package.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\Unity.*.nupkg'
  name: 'Abstractions'
