name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    

jobs:

  build:
    runs-on: windows-latest
    env:
      PackagePath: '${{ github.workspace }}\package'
      ProjectPath:  '${{ github.workspace }}\src\Unity.Abstractions.csproj'
      TestsPath:       '${{ github.workspace }}\tests\Unity.Abstractions.Tests.csproj'

    steps:

    - name: Checkout Container
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master        
      with:
        path: Container

    - name: Setup local NuGet source
      run: dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text

    - name: Add GitVersion and SourceLink packages
      run: | 
        dotnet add ${{ env.ProjectPath }} package GitVersionTask --no-restore
        dotnet add ${{ env.ProjectPath }} package Microsoft.SourceLink.GitHub

    - name: Build
      run: | 
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ env.ProjectPath }}
      #  dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ env.TestsPath }}

    # - name: Test
    #   run: | 
    #     dotnet test ${{ env.TestsPath }}

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackagePath }}\*' --skip-duplicate --source github
