name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: https://github.com/unitycontainer/github/.github/workflows/cd-flow.yml@main
    # with:
      # config-path: .github/gitversion.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  