name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: unitycontainer/unity/blob/workflows/.github/workflows/continuous-deployment-flow.yml@workflows
    secrets: inherit
  