name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    

jobs:
  call-workflow:
    uses: unitycontainer/unity/.github/workflows/continuous-deployment-flow.yml@workflows

# jobs:
#   call-workflow-passing-data:
#     permissions:
#       contents: read
#       pull-requests: write
#     secrets: inherit
  