name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    
 
jobs: 

  build-package-flow:
    uses: unitycontainer/.github/.github/workflows/build-package-flow.yml@main
    secrets: inherit 

  publish-artifact-flow:
    needs: [ build-package-flow ]
    uses: unitycontainer/.github/.github/workflows/publish-artifact-flow.yml@main
    secrets: inherit
